### ISSUE TITLE
Unknown method

### ISSUE THREAD

**Issue by lordnynex** [leafo/luarocks-site#15]
Hello! Sorry for all the bugs this morning. I use this repository as supplemental documentation for lapis. I've really learned a lot from just reading how this site works. One thing I have not been able to resolve yet is the reference to ```@check_unique_constraint```. I've used github search to try and find it's definition but I've come up empty. Did I just not look hard enough? 

https://github.com/leafo/moonrocks-site/blob/master/models/users.moon#L17

I'm simply trying to figure out how to fail gracefully on duplicate keys.

**Comment by leafo** [comment]
Sorry for not responding sooner. Here's the check constraint implementation if you didn't find it: https://github.com/leafo/lapis/blob/master/lapis/db/base_model.moon#L295

It's currently undocumented part of lapis because I'm unsure about the api and implementation.
