### ISSUE TITLE
Issue with & in password reset link sent by e-mail

### ISSUE THREAD

**Issue by askyrme** [leafo/luarocks-site#20]
Hello,

It appears there is an issue with the link sent by e-mail for password reset. The & character is being placed, as in HTML, as `&amp;` and that breaks the link. For example, I just received the following (token sanitized) password reset link:

http://rocks.moonscript.org/user/forgot_password?token=[sanitized]&amp;id=97

When I tried to access it, it reports an error: "id must be an integer". I was able to access it properly by simply deleting the amp; and leaving &id=97. Not only the link's text shows the `&amp;`, but also the link's reference (href) includes the `&amp;`.

**Comment by leafo** [comment]
Hello,

I'm going through old issues. I just tested sending password reset email to myself and wasn't able to reproduce. If you're still having the issue could you tell me which mail client you are using so I can investigate more.

THanks
