### ISSUE TITLE
luarocks on Mac requires --server

### ISSUE THREAD

**Issue by starius** [leafo/luarocks-site#23]
Command `sudo luarocks install lapis` does not work by default on Mac:
Error: No results matching query were found.

Command `sudo luarocks install --server=http://rocks.moonscript.org lapis` works on Mac.

I think this should be mentioned on moonrocks site and/or on lapis site.

**Comment by sbuettner** [comment]
Had the same issue. Thank you @starius for posting your solution.

**Comment by leafo** [comment]
This shouldn't be happening, how old is your version of luarocks? The default luarocks should point to luarocks.org, which is now what rocks.moonscript.org was.

**Comment by sbuettner** [comment]
Seems to be resolved when using a more recent version (```luarocks 2.2.1```).
