### ISSUE TITLE
Deleting a single rock

### ISSUE THREAD

**Issue by daurnimator** [leafo/luarocks-site#31]
The binary rock I uploaded (for systemd) is compiled against lua 5.2 on a computer with quite a new glibc. Hence it is incompatible with systems that use 5.1, or an older glibc...
How can I delete it?
(without deleting the rockspec/source rock too; or messing up stats)

**Comment by leafo** [comment]
Currently isn't a way to delete it, I'll have to add something. You can overwrite it though if you upload a rock with the same name.

**Comment by daurnimator** [comment]
> You can overwrite it though if you upload a rock with the same name.

The problem is that you can only have one binary rock for each architecture (i think?), when I tried to run [the binary rock](https://rocks.moonscript.org/manifests/daurnimator/systemd-scm-0.linux-x86_64.rock) with lua 5.1 it failed because it couldn't find the 5.2 function `luaL_setfuncs` it was compiled against.

So I'd like to remove/delete the binary rock; but not the rockspec or src rock.

**Comment by daurnimator** [comment]
Any movement on this issue?

**Comment by leafo** [comment]
sorry haven't had a chance yet
