### ISSUE TITLE
Move rocks.moonscript.org -> luarocks.org

### ISSUE THREAD

**Issue by leafo** [leafo/luarocks-site#40]
* [x] Buy SSL cert
* [x] Remove luarocks.org -> rocks.moonscript.org redirects
* [x] Write logic to redirect any rocks.moonscript.org urls to the appropriate luarocks.org versions
* [x] Rename github repo to luarocks-site

**Comment by daurnimator** [comment]
Need a hand here?

**Comment by leafo** [comment]
I don't think so, changes are all pretty minor.

**Comment by leafo** [comment]
All done :)
