### ISSUE TITLE
Improve luarocks.org front page

### ISSUE THREAD

**Issue by rrthomas** [leafo/luarocks-site#41]
1. Explain what it is in BIG LETTERS near the top of the page, like http://npmjs.org/

2. Change the "Download" link (download what? one may ask). Putting "Install" might be better; but "Install LuaRocks" is perhaps ambiguous. npmjs.org has a link with some explanation "beneath the fold". I suspect given their popularity they're a good model to follow if you don't have a better idea.

3. I mistakenly filed this issue first on the LuaRocks github; add a "Report site bug" link (I know, there's already a "Source" link, that could better be "Site source" as well!).

**Comment by leafo** [comment]
I ended of taking a lot of your suggestions a while ago. If you have any other issues feel free to let me know.

**Comment by rrthomas** [comment]
Nice work, the current design is a huge improvement.
