### ISSUE TITLE
*.src.rock isn't uploaded to rocks.moonscript.org

### ISSUE THREAD

**Issue by starius** [leafo/luarocks-site#49]
I'm uploading [my rock][1] to https://rocks.moonscript.org. I've uploaded both *.rockspec and *.src.rock, but [only the first one][2] can be downloaded back from the site. For other rocks both files can be downloaded. How can I fix this?

[1]: http://rocks.moonscript.org/modules/starius/lua-rote
[2]: https://rocks.moonscript.org/modules/starius/lua-rote/1.0.1-1

**Comment by leafo** [comment]
How are you uploading the source rock? Do you let the command line tool create it and upload it for you or do you create it yourself and upload from web interface? Are you getting any error messages when you do it?

**Comment by starius** [comment]
I create the source rock myself and upload from web interface. I am not getting any error messages.

**Comment by leafo** [comment]
Going through old issues. I wasn't able to reproduce this. I could upload both rockspec and rock at same time successfully through web interface. If you're still having the issue send me a link to the problematic files.
