### ISSUE TITLE
Releases page is gone

### ISSUE THREAD

**Issue by Choonster** [leafo/luarocks-site#52]
Clicking the Install link at the top of the site leads to [this wiki page](https://github.com/keplerproject/luarocks/wiki/Download), which links to http://luarocks.org/releases; but that page doesn't exist any more.

Where can LuaRocks (specifically the Windows package) be downloaded from the website?

**Comment by leafo** [comment]
Try again, the redirect was only matching for `/releases/` but now also works for `/releases`.

Thanks

**Comment by Choonster** [comment]
That works now, thanks.
