### ISSUE TITLE
Error: No results matching query were found, Mac OS 10.10.3

### ISSUE THREAD

**Issue by mdiephuis** [leafo/luarocks-site#56]
I'm on luarocks 2.2.1, lua 5.2.3, mac os 10.10.3, have the zip util, and running:

'luarocks install --verbose --only-server=http://rocks.moonscript.org optim' gives:

io.popen: 	'pwd'

os.execute: 	cd '/opt/luarocks-2.2.1' && test '-e' '/usr/local/lib/luarocks/rocks'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/opt/luarocks-2.2.1' && test '-d' '/usr/local/lib/luarocks/rocks'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/opt/luarocks-2.2.1' && test '-e' '/usr/local'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/opt/luarocks-2.2.1' && test '-d' '/usr/local'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/opt/luarocks-2.2.1' && test '-e' '/usr/local'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/opt/luarocks-2.2.1' && mkdir -p '/Users/Maurits/.cache/luarocks/http___rocks.moonscript.org'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/opt/luarocks-2.2.1' && 'curl' -k -f -L --user-agent 'LuaRocks/2.2.1 macosx-x86_64 via curl' --connect-timeout 30 'http://rocks.moonscript.org/manifest-5.2.zip' 2> /dev/null 1> '/Users/Maurits/.cache/luarocks/http___rocks.moonscript.org/manifest-5.2.zip'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/opt/luarocks-2.2.1' && test '-d' '/Users/Maurits/.cache/luarocks/http___rocks.moonscript.org'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/Users/Maurits/.cache/luarocks/http___rocks.moonscript.org' && rm '-rf' '/Users/Maurits/.cache/luarocks/http___rocks.moonscript.org/manifest-5.2'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/Users/Maurits/.cache/luarocks/http___rocks.moonscript.org' && unzip -n '/Users/Maurits/.cache/luarocks/http___rocks.moonscript.org/manifest-5.2.zip'
Archive:  /Users/Maurits/.cache/luarocks/http___rocks.moonscript.org/manifest-5.2.zip
  inflating: manifest-5.2
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

Error: No results matching query were found.

**Comment by leafo** [comment]
I don't see a package named optim on http://luarocks.org

**Comment by mdiephuis** [comment]
Me mistake, this library is a part of torch.
