### ISSUE TITLE
I cound't able to use luarocks with lua 5.3

### ISSUE THREAD

**Issue by quiloos39** [leafo/luarocks-site#60]
I am running Ubuntu Server 15.04 on VM , I used these commands to install lua and luarocks

sudo apt-get install unzip
sudo apt-get install gcc
wget http://www.lua.org/ftp/lua-5.3.1.tar.gz
tar zxf lua-5.3.1.tar.gz
cd lua-5.3.1
sudo make solaris test
sudo make solaris install
reboot
wget http://luarocks.org/releases/luarocks-2.2.1.tar.gz
tar zxpf luarocks-2.2.1.tar.gz
cd luarocks-2.2.1
./configure; sudo make bootstrap
sudo luarocks install luasocket

lua -lsocket -- It errors.
<img width="724" alt="screen shot 2015-07-24 at 3 36 57 pm" src="https://cloud.githubusercontent.com/assets/10371011/8874460/e828f40e-3219-11e5-8cb4-365cc298df44.png">

<img width="720" alt="screen shot 2015-07-24 at 3 32 52 pm" src="https://cloud.githubusercontent.com/assets/10371011/8874406/62f4266e-3219-11e5-8f19-ff40ff15ed00.png">

<img width="719" alt="screen shot 2015-07-24 at 3 33 23 pm" src="https://cloud.githubusercontent.com/assets/10371011/8874407/62f511dc-3219-11e5-9994-61c1ec6ab6bb.png">

**Comment by leafo** [comment]
Hello, please send issues with luarocks itself to the [luarocks repository](https://github.com/keplerproject/luarocks/issues).
