### ISSUE TITLE
Failed loading manifest

### ISSUE THREAD

**Issue by zeis** [leafo/luarocks-site#71]
Hello,

I've just installed luarocks on Mac OSX 10.11 using Homebrew (as suggested in the installation page). Now, I do not understand the following warning message after running `luarocks list`. What does it mean? Is there a way to fix this problem? 

    Warning: Failed loading manifest for /Users/zeis/.luarocks/lib/luarocks/rocks-5.2:/Users/zeis/.luarocks/lib/luarocks/rocks-5.2/manifest: No such file or directory

    Installed rocks:
    ----------------

    ansicolors
       1.0.2-3 (installed) - /usr/local/lib/luarocks/rocks-5.2

    lua-cjson
       2.1.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

    luafilesystem
       1.6.3-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

    luasocket
       3.0rc1-2 (installed) - /usr/local/lib/luarocks/rocks-5.2

    moonrocks
       1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

    penlight
       1.3.2-2 (installed) - /usr/local/lib/luarocks/rocks-5.2

**Comment by leafo** [comment]
Looks like an issue for the luarocks command line tool, you can post here: https://github.com/keplerproject/luarocks/issues

**Comment by zeis** [comment]
I solved. I was a configuration problem with 'wget'. Thank you.
