### ISSUE TITLE
Missing dependency in BoxFile – bcrypt

### ISSUE THREAD

**Issue by jirutka** [leafo/luarocks-site#73]
[models/Users.lua:10](https://github.com/leafo/luarocks-site/blob/c8d2c2295eb30e8504823f5b22cd3e2be1a5218e/models/users.moon#L10) requires `bcrypt` that is not listed in BoxFile.

**Comment by leafo** [comment]
It's right here: https://github.com/leafo/luarocks-site/blob/master/BoxFile#L8

**Comment by jirutka** [comment]
Uh, I don’t understand why it didn’t work. Nevermind, I’m obviously blind and the problem must be elsewhere.
