### ISSUE TITLE
"luarestyredis" rock is installing in wrong path so other packages can't find it.

### ISSUE THREAD

**Issue by jamesbjackson** [leafo/luarocks-site#76]
I hope this is correct place to raise this issue. For the following Lua rock "https://luarocks.org/modules/uuser/luarestyredis"

This is installed in the following following folder in linux "/usr/local/share/lua/5.1/redis.lua" but should be "/usr/local/share/lua/5.1/resty/redis.lua" is this something that can be addressed?

**Comment by leafo** [comment]
looks like @uu uploaded the rockspec

**Comment by leafo** [comment]
Issues with modules should be redirected to the owner. Closing this.
