### ISSUE TITLE
How exactly does search in luarocks.org work?

### ISSUE THREAD

**Issue by hishamhm** [leafo/luarocks-site#81]
AFAICT search includes the description fields (nice!), e.g.

* https://luarocks.org/search?q=dispatch
 * Returns useful results where "dispatch" features in the extended description
* https://luarocks.org/search?q=protocol
 * This returns many matches including https://luarocks.org/modules/akhaustov/lua-pb

But these searches gave me surprising results:

* https://luarocks.org/search?q=protocol+buffers
 * This returns no matches, even though th description of lua-pb is "Lua Protocol Buffers"
* https://luarocks.org/search?q=%22protocol+buffers%22
 * No matches either
* https://luarocks.org/search?q=lua-pb
 * This returns many matches but lua-pb itself is buried near the end of the list, perhaps an exact match should be moved to the top?

**Comment by leafo** [comment]
Not very well, I need to spend some time tweaking it.

Right now it uses postgres fulltext search, indexed on a concatenation of the module title, summary, and description: https://github.com/leafo/luarocks-site/blob/master/models/modules.moon#L80 (the index is described here: https://github.com/leafo/luarocks-site/blob/master/models/modules.moon#L39)

Another fatal flaw is that it currently sorts by downloads for whatever reason.

"protocol buffers" not matching is strange, I think there's a bug somewhere that's misinterpreting the space as a different character (looks like a +). Additionally direct matches should definitely be bumped to the top (and if there are multiple it makes sense to sort by downloads there)

**Comment by leafo** [comment]
It's not perfect yet, but should be significantly improved

**Comment by leafo** [comment]
Okay it should be much better now.

There are still some things that can be improved, for example

searching for "lua socket" or "socket" does not find "LuaSocket"

I'm going to create a general issue where people can post issues where search isn't returning what they expect.
