### ISSUE TITLE
stdin:1: module 'socket' not found:

### ISSUE THREAD

**Issue by phobrain** [leafo/luarocks-site#90]
On OSX, Darwin Kernel Version 15.0.0

  564  wget http://luarocks.org/releases/luarocks-2.3.0.tar.gz
  565  ls
  566  tar zxpf luarocks-2.3.0.tar.gz
  567  cd luarocks-2.3.0
  568  ./configure; sudo make bootstrap
  569  sudo luarocks install luasocket

% lua
Lua 5.3.1  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> require "socket"
stdin:1: module 'socket' not found:
    no field package.preload['socket']
    no file '/opt/local/share/lua/5.3/socket.lua'
    no file '/opt/local/share/lua/5.3/socket/init.lua'
    no file '/opt/local/lib/lua/5.3/socket.lua'
    no file '/opt/local/lib/lua/5.3/socket/init.lua'
    no file './socket.lua'
    no file './socket/init.lua'
    no file '/opt/local/lib/lua/5.3/socket.so'
    no file '/opt/local/lib/lua/5.3/loadall.so'
    no file './socket.so'
stack traceback:
    [C]: in function 'require'
    stdin:1: in main chunk
    [C]: in ?

Also tried

  575  luarocks --local install luasocket

Same result.

**Comment by phobrain** [comment]
Looks like an EOL package.

**Comment by leafo** [comment]
Sounds like a configuration issue. This issue tracker is only for the luarocks website, not the actual tool. If you've found a big you can post here: https://github.com/keplerproject/luarocks
