### ISSUE TITLE
Makefile:2: config.unix: No such file or directory

### ISSUE THREAD

**Issue by 55jr55** [leafo/luarocks-site#96]
Install fails on 3.19.0-56-generic #62~14.04.1-Ubuntu:
jreynolds@build3-usg:~/4230/opensrc/luarocks-2.4.0$ ./configure; sudo make bootstrap
Looking for Lua... lua not found in $PATH.
You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help.

configure failed.

Makefile:2: config.unix: No such file or directory
make: *** No rule to make target `config.unix'.  Stop.

**Comment by leafo** [comment]
Hello,

This is the for luarocks website, not the command line tool. You can open an issue here: https://github.com/keplerproject/luarocks/issues
