### ISSUE TITLE
module not included in root manifest

### ISSUE THREAD

**Issue by zandbelt** [leafo/luarocks-site#97]
AFAICT this rock https://luarocks.org/modules/hanszandbelt/lua-resty-openidc should be included in the root manifest, but apparently it isn't. What do I need to do to correct this?

Perhaps related: I am also not sure why I need to set "Include non-root" to be able to search it from: https://luarocks.org/search?q=lua-resty-openidc

**Comment by leafo** [comment]
By default, when uploading a new module it will be added to the root manifest unless the name is already taken. How did you upload your module? Was it through the command line tool or the web interface?

In any case, you can add your module by clicking the "Add to manifest" link on the top of the page when logged in as the module owner.

**Comment by zandbelt** [comment]
I uploaded it through the commandline tool.

I've manually added it now, thanks (I had not realized I was not logged in).
